### ISSUE TITLE
Bug with suffixes

### ISSUE THREAD

**Issue by jrunning** [gfx/ruby-regexp_trie#1]
I think I've stumbled across a bug. I'm using RegexpTrie 0.2.0.

Take this example from the [tests](https://github.com/gfx/ruby-regexp_trie/blob/bd1d965c11b53a9967cfb68d819a027916d935b1/test/regexp_trie_test.rb):

``` ruby
RegexpTrie.union("foo", "foobar", "foobaz")
```

I would expect this to produce a Regexp like, say, `/foo(?:ba[rz])?/`, but instead it produces `/foo(?:)?/`.

This is significant because I often use `Regexp.union` like this:

``` ruby
words = [ "foo", "foobar", "foobaz" ]
expr = /\b#{Regexp.union("foo", "foobar", "foobaz")}\b/ # => /\b(?-mix:foo|foobar|foobaz)\b/
assert(expr === "text foobar text")
```

But this doesn't work with `RegexpTrie.union`:

``` ruby
words = [ "foo", "foobar", "foobaz" ]
expr = /\b#{RegexpTrie.union("foo", "foobar", "foobaz")}\b/ # => /\b(?-mix:foo(?:)?)\b/
assert(expr === "text foobar text")
# => Test::Unit::AssertionFailedError: <false> is not true.
```

**Comment by gfx** [comment]
Thanks. It was a bug. Released v0.3.0.
