### ISSUE TITLE
#union ignores blank string.

### ISSUE THREAD

**Issue by tadyjp** [gfx/ruby-regexp_trie#3]
```
Regexp.union(['a', ''])
=> /(?-mix:a|)/

RegexpTrie.union(['a', ''])
=> /(?-mix:a)/
```

**Comment by gfx** [comment]
I think this is a spec. In fact, this is not a drop-in replacement to `Regexp.union()`.

There are some incompatibilities with `Regexp.union()` so they are now added to README: e5ef61d

**Comment by tadyjp** [comment]
Thanks for your comment!
